SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

CREATE TABLE `messages` (
  `id` int(11) NOT NULL,
  `previousWord` text,
  `secondLastWord` text,
  `content` text NOT NULL,
  `channel` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT;

CREATE TABLE `words` (
  `id` int(11) NOT NULL,
  `word` text NOT NULL,
  `previousWord` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=COMPACT;


ALTER TABLE `messages`
  ADD PRIMARY KEY (`id`);
ALTER TABLE `messages`
  ADD FULLTEXT KEY `previousWord` (`previousWord`);
ALTER TABLE `messages`
  ADD FULLTEXT KEY `secondLastWord` (`secondLastWord`);

ALTER TABLE `words`
  ADD PRIMARY KEY (`id`);
ALTER TABLE `words`
  ADD FULLTEXT KEY `previousWord` (`previousWord`);


ALTER TABLE `messages`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=0;
ALTER TABLE `words`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=0;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
